/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view.renderer;

import java.awt.Color;
import java.awt.Component;
import java.util.Locale;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import katic.ljetnizadatak.model.Jelo;

/**
 *
 * @author Valentin
 */
public class RendererJelaUKategoriji extends javax.swing.JPanel implements ListCellRenderer{

    /**
     * Creates new form Renderer
     */
    public RendererJelaUKategoriji() {
        initComponents();
//        setForeground(new java.awt.Color(204, 204, 204));
//        setFont(new java.awt.Font("Century Gothic", 0, 14));
//        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    }
    
    @Override
    public Component getListCellRendererComponent(JList list, Object value,
        int index, boolean isSelected, boolean cellHasFocus) {
       
        Jelo entry = (Jelo) value;       
        lblNaziv.setText(entry.getNaziv());
        String sastojci = entry.getSastojci();
        if (sastojci.length()>40){
            sastojci = sastojci.substring(0,37) + "...";
        }
        lblSastojci.setText(sastojci);
        lblSastojci.setToolTipText(entry.getSastojci());
        lblCijena.setText(String.format(Locale.getDefault(), "%.2f kn", entry.getCijena()));
       
        if (isSelected) {
          setBackground(new Color(38,40,55));
        } else {
          setBackground(new Color(58,56,77));
        }        
        
        return this;
  }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNaziv = new javax.swing.JLabel();
        lblSastojci = new javax.swing.JLabel();
        lblCijena = new javax.swing.JLabel();

        setBackground(new java.awt.Color(58, 56, 77));
        setLayout(new java.awt.GridBagLayout());

        lblNaziv.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNaziv.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv.setText("Naziv");
        lblNaziv.setPreferredSize(new java.awt.Dimension(310, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(lblNaziv, gridBagConstraints);

        lblSastojci.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblSastojci.setForeground(new java.awt.Color(255, 255, 255));
        lblSastojci.setText("Sastojci");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(lblSastojci, gridBagConstraints);

        lblCijena.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCijena.setForeground(new java.awt.Color(255, 255, 255));
        lblCijena.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCijena.setText("Cijena");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(lblCijena, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCijena;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblSastojci;
    // End of variables declaration//GEN-END:variables
}
