/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.TrayIcon;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import katic.ljetnizadatak.controller.HibernateObrada;
import katic.ljetnizadatak.model.Jelo;
import katic.ljetnizadatak.model.KategorijaJela;
import katic.ljetnizadatak.model.Restoran;
import katic.pomocno.HibernateUtil;

/**
 *
 * @author valentin.katic
 */
public class FormaJelo extends Forma<Jelo> {

    private Restoran restoran;
    private List<KategorijaJela> kategorijeJela;
    private List<Jelo> jela;
    private int indeksKategorije = -1;
    /**
     * Creates new form FormaJelo
     */
    public FormaJelo(Restoran restoran) {
        this.restoran = restoran;
        initComponents();
        
        Image plusImage = new ImageIcon(getClass().getResource("/res/plus_icon.png")).getImage();
        plusImage = getScaledImage(plusImage, 16, 16);
        icoPlus.setIcon(new ImageIcon(plusImage));
        
        obrada = new HibernateObrada();     
        
        ucitaj();        
    }
    
    @Override
    protected void ucitaj(){
        kategorijeJela = HibernateUtil
                .getSession()
                .createQuery("from KategorijaJela k where k.obrisan=false")              
                .list();
        DefaultListModel<KategorijaJela> m = new DefaultListModel<KategorijaJela>();
        lstKategorije.setModel(m);
        DefaultComboBoxModel<KategorijaJela> cbm = new DefaultComboBoxModel<>();
        cmbKategorije.setModel(cbm);
        
        for (KategorijaJela k: kategorijeJela){
            m.addElement(k);
            cbm.addElement(k);
        }    
         
        cmbKategorije.setSelectedIndex(-1);
        if (indeksKategorije>-1){
            lstKategorije.setSelectedIndex(indeksKategorije);
        }
        
        System.out.println("indeksKategorije "+indeksKategorije);
    }
    
    private void ucitajJela(){
        if (lstKategorije.getSelectedValue()==null){
            return;
        }      
        cmbKategorije.setSelectedIndex(-1);
        jela = HibernateUtil
                .getSession()
                .createQuery("from Jelo j where "
                        + "j.obrisan=false AND j.kategorijaJela= :kategorijaJela "
                        + "AND j.restoran= :restoran")  
                .setLong("kategorijaJela", lstKategorije.getSelectedValue().getSifra())
                .setLong("restoran", restoran.getSifra())
                .list();
        DefaultListModel<Jelo> m = new DefaultListModel<Jelo>();
        lstJela.setModel(m);
        for (Jelo j: jela){
            m.addElement(j);
        }     
        if (entitet!=null){            
            lstJela.setSelectedValue(entitet, rootPaneCheckingEnabled);
        }
        
    }
    
    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();

        return resizedImg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstKategorije = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        icoPlus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstJela = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSastojci = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCijena = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnPromijeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbKategorije = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstKategorije.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKategorijeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstKategorije);

        jLabel1.setText("Kategorije");

        icoPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icoPlusMouseClicked(evt);
            }
        });

        jLabel2.setText("Jela");

        lstJela.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstJelaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstJela);

        jLabel3.setText("Naziv");

        jLabel4.setText("Sastojci");

        jLabel5.setText("Cijena");

        jLabel6.setText("kn");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromijeni.setText("Promijeni");
        btnPromijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromijeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel7.setText("Kategorija");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(txtSastojci, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnPromijeni))
                            .addComponent(jLabel7)
                            .addComponent(cmbKategorije, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2)
                                .addGap(0, 318, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(icoPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisi)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSastojci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbKategorije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromijeni))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoPlus)
                    .addComponent(btnObrisi))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        indeksKategorije = lstKategorije.getSelectedIndex();
        entitet = new Jelo();
        entitet.setNaziv(txtNaziv.getText());
        entitet.setSastojci(txtSastojci.getText());
        entitet.setCijena(Double.parseDouble(txtCijena.getText()));
        entitet.setKategorijaJela(lstKategorije.getSelectedValue());
        entitet.setRestoran(restoran);
        spremi();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromijeniActionPerformed
        indeksKategorije = cmbKategorije.getSelectedIndex();
        entitet.setSifra(lstJela.getSelectedValue().getSifra());
        entitet.setNaziv(txtNaziv.getText());
        entitet.setSastojci(txtSastojci.getText());
        entitet.setCijena(Double.parseDouble(txtCijena.getText()));
        entitet.setKategorijaJela((KategorijaJela)cmbKategorije.getSelectedItem());
        spremi();
    }//GEN-LAST:event_btnPromijeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        indeksKategorije = lstKategorije.getSelectedIndex();
        obrisi();
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void icoPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icoPlusMouseClicked
        try {
            String kategorija = JOptionPane.showInputDialog(this, "Unesite naziv kategorije", "Nova kategorija", JOptionPane.INFORMATION_MESSAGE);
            HibernateObrada<KategorijaJela> obradaKategorijaJela = new HibernateObrada<>();
            KategorijaJela kj = new KategorijaJela();
            kj.setNaziv(kategorija);
            obradaKategorijaJela.save(kj);
            ucitaj();
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_icoPlusMouseClicked

    private void lstKategorijeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKategorijeValueChanged
        ocistiFormu();
        ucitajJela();
        KategorijaJela k = lstKategorije.getSelectedValue();
        cmbKategorije.setSelectedItem(k);
    }//GEN-LAST:event_lstKategorijeValueChanged

    private void ocistiFormu(){
        txtNaziv.setText("");
        txtSastojci.setText("");           
        txtCijena.setText("");
    }
    
    private void lstJelaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstJelaValueChanged
        if (lstJela.getSelectedValue()!=null){
            entitet = lstJela.getSelectedValue();
            try{
                txtNaziv.setText(entitet.getNaziv());
                txtSastojci.setText(entitet.getSastojci());           
                txtCijena.setText(Double.toString(entitet.getCijena()));
            } catch (Exception e){
                e.printStackTrace();
                ocistiFormu();
            }
        }
    }//GEN-LAST:event_lstJelaValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromijeni;
    private javax.swing.JComboBox<KategorijaJela> cmbKategorije;
    private javax.swing.JLabel icoPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Jelo> lstJela;
    private javax.swing.JList<KategorijaJela> lstKategorije;
    private javax.swing.JTextField txtCijena;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSastojci;
    // End of variables declaration//GEN-END:variables
}
