/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author valentin.katic
 */
public class FormaAplikacije extends javax.swing.JFrame {

    /**
     * Creates new form FormaObrazacZaPrijavu
     */
    public FormaAplikacije() {
        initComponents();
        
        lijeviPanel.add(new PanelPrijave());        
        desniPanel.add(new PanelRegistracije());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lijeviPanel = new javax.swing.JPanel();
        desniPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ljetni zadatak");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(700,500);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lijeviPanel.setBackground(new java.awt.Color(38, 40, 55));
        lijeviPanel.setMaximumSize(new java.awt.Dimension(300, 500));
        lijeviPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        lijeviPanel.setPreferredSize(new java.awt.Dimension(300, 500));

        javax.swing.GroupLayout lijeviPanelLayout = new javax.swing.GroupLayout(lijeviPanel);
        lijeviPanel.setLayout(lijeviPanelLayout);
        lijeviPanelLayout.setHorizontalGroup(
            lijeviPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        lijeviPanelLayout.setVerticalGroup(
            lijeviPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(lijeviPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));
        lijeviPanel.getAccessibleContext().setAccessibleName("");

        desniPanel.setBackground(new java.awt.Color(58, 56, 77));
        desniPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        desniPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        desniPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(desniPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaAplikacije().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel desniPanel;
    private javax.swing.JPanel lijeviPanel;
    // End of variables declaration//GEN-END:variables
}
