/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.DefaultListModel;
import katic.ljetnizadatak.controller.ObradaNarudzba;
import katic.ljetnizadatak.model.Narudzba;
import katic.ljetnizadatak.model.Restoran;
import katic.ljetnizadatak.view.renderer.RendererNarudzbi;
import katic.pomocno.MenuListener;

/**
 *
 * @author valentin.katic
 */
public class PanelNarudzbe extends javax.swing.JPanel {

    private ObradaNarudzba obrada;
    private Restoran restoran;
    private Narudzba narudzba;
    /**
     * Creates new form PanelRestoran
     */
    private MenuListener menuListener;
    
    public PanelNarudzbe(MenuListener menuListener, Restoran restoran) {
        initComponents();
        this.menuListener = menuListener;
        this.restoran = restoran;
        
        this.obrada = new ObradaNarudzba();      
        ucitaj();
    }

    private void ucitaj(){
        DefaultListModel<Narudzba> m = new DefaultListModel<Narudzba>();
        lista.setModel(m);
        List<Narudzba> narudzbe = obrada.getSveNarudzbeOdRestorana(restoran);
        Collections.sort(narudzbe, new Comparator<Narudzba>() {
            @Override
            public int compare(Narudzba t, Narudzba t1) {
                return t1.getVrijemeNarudzbe().compareTo(t.getVrijemeNarudzbe());
            }
        });
        
        for (Narudzba r: narudzbe){
            m.addElement(r);
        }
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setBackground(new java.awt.Color(58, 56, 77));
        setForeground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBorder(null);

        lista.setBackground(new java.awt.Color(58, 56, 77));
        lista.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lista.setFont(new java.awt.Font("Century Gothic", 0, 28)); // NOI18N
        lista.setForeground(new java.awt.Color(204, 204, 204));
        lista.setToolTipText("");
        lista.setCellRenderer(new RendererNarudzbi());
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        if (lista.getSelectedValue()==null){
            return;
        }
        narudzba = lista.getSelectedValue();
        menuListener.odabranaNarudzba(narudzba, null);
        lista.clearSelection();
    }//GEN-LAST:event_listaValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Narudzba> lista;
    // End of variables declaration//GEN-END:variables
}
