/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import katic.ljetnizadatak.model.Tab;
import katic.pomocno.PomagalaIzbornika;
import katic.pomocno.StartPanelListener;

/**
 *
 * @author Valentin
 */
public class PanelStart extends javax.swing.JPanel {

    private StartPanelListener startPanelListener;
    private int pressedTab = 0;
    private List<Tab> tabovi = new ArrayList<>();
    /**
     * Creates new form PanelStart
     */
    public PanelStart(StartPanelListener startPanelListener) {
        initComponents();
        
        tabovi.add(new Tab(lblPrijava, FormaAplikacije.PRIJAVA));
        tabovi.add(new Tab(lblRegistracija, FormaAplikacije.REGISTRACIJA));
        this.startPanelListener = startPanelListener;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistracija = new javax.swing.JLabel();
        lblPrijava = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 40, 55));

        lblRegistracija.setBackground(new java.awt.Color(38, 40, 55));
        lblRegistracija.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblRegistracija.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/signup.png"))); // NOI18N
        lblRegistracija.setText("Registracija");
        lblRegistracija.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblRegistracija.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblRegistracija.setOpaque(true);
        lblRegistracija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistracijaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistracijaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistracijaMouseExited(evt);
            }
        });

        lblPrijava.setBackground(new java.awt.Color(58, 56, 77));
        lblPrijava.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblPrijava.setForeground(new java.awt.Color(204, 204, 204));
        lblPrijava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/signin.png"))); // NOI18N
        lblPrijava.setText("Prijava");
        lblPrijava.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblPrijava.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblPrijava.setOpaque(true);
        lblPrijava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrijavaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrijavaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrijavaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistracija, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrijava, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblPrijava)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistracija)
                .addContainerGap(313, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrijavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrijavaMouseClicked
        pressedTab = PomagalaIzbornika.setClickedEffect(tabovi, (JLabel)evt.getComponent(), startPanelListener);
    }//GEN-LAST:event_lblPrijavaMouseClicked

    private void lblRegistracijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistracijaMouseClicked
        pressedTab = PomagalaIzbornika.setClickedEffect(tabovi, (JLabel)evt.getComponent(), startPanelListener);
    }//GEN-LAST:event_lblRegistracijaMouseClicked

    private void lblPrijavaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrijavaMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_lblPrijavaMouseExited

    private void lblPrijavaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrijavaMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_lblPrijavaMouseEntered

    private void lblRegistracijaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistracijaMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_lblRegistracijaMouseEntered

    private void lblRegistracijaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistracijaMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_lblRegistracijaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPrijava;
    private javax.swing.JLabel lblRegistracija;
    // End of variables declaration//GEN-END:variables
}
