/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import katic.ljetnizadatak.FormaAplikacije;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import katic.ljetnizadatak.model.Tab;
import katic.pomocno.PomagalaIzbornika;
import katic.pomocno.MenuListener;

/**
 *
 * @author Valentin
 */
public class PanelStart extends javax.swing.JPanel {

    private MenuListener menuListener;
    private int pressedTab = 0;
    private List<Tab> tabovi = new ArrayList<>();
    
    public PanelStart(MenuListener menuListener) {
        initComponents();
        
        tabovi.add(new Tab(lblPrijava, FormaAplikacije.PRIJAVA));
        tabovi.add(new Tab(lblRegistracija, FormaAplikacije.REGISTRACIJA));
        this.menuListener = menuListener;
    }

    public void setTabPrijave(){
        pressedTab = 0;
        PomagalaIzbornika.setClickedEffect(tabovi, lblPrijava, menuListener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistracija = new javax.swing.JLabel();
        lblPrijava = new javax.swing.JLabel();
        btnGitHub = new javax.swing.JLabel();
        btnImportPodataka = new javax.swing.JLabel();
        btnERADijagram = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 40, 55));

        lblRegistracija.setBackground(new java.awt.Color(38, 40, 55));
        lblRegistracija.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblRegistracija.setForeground(new java.awt.Color(204, 204, 204));
        lblRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/signup.png"))); // NOI18N
        lblRegistracija.setText("Registracija");
        lblRegistracija.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblRegistracija.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblRegistracija.setOpaque(true);
        lblRegistracija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistracijaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistracijaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistracijaMouseExited(evt);
            }
        });

        lblPrijava.setBackground(new java.awt.Color(58, 56, 77));
        lblPrijava.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblPrijava.setForeground(new java.awt.Color(204, 204, 204));
        lblPrijava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/signin.png"))); // NOI18N
        lblPrijava.setText("Prijava");
        lblPrijava.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblPrijava.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblPrijava.setOpaque(true);
        lblPrijava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrijavaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrijavaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrijavaMouseExited(evt);
            }
        });

        btnGitHub.setBackground(new java.awt.Color(38, 40, 55));
        btnGitHub.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnGitHub.setForeground(new java.awt.Color(204, 204, 204));
        btnGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/github.png"))); // NOI18N
        btnGitHub.setText("GitHub");
        btnGitHub.setToolTipText("https://github.com/valentinkatic/LjetniZadatak");
        btnGitHub.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGitHub.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        btnGitHub.setOpaque(true);
        btnGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGitHubMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGitHubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGitHubMouseExited(evt);
            }
        });

        btnImportPodataka.setBackground(new java.awt.Color(38, 40, 55));
        btnImportPodataka.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnImportPodataka.setForeground(new java.awt.Color(204, 204, 204));
        btnImportPodataka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/import.png"))); // NOI18N
        btnImportPodataka.setText("Import podataka");
        btnImportPodataka.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnImportPodataka.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        btnImportPodataka.setOpaque(true);
        btnImportPodataka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportPodatakaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImportPodatakaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImportPodatakaMouseExited(evt);
            }
        });

        btnERADijagram.setBackground(new java.awt.Color(38, 40, 55));
        btnERADijagram.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnERADijagram.setForeground(new java.awt.Color(204, 204, 204));
        btnERADijagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/diagram.png"))); // NOI18N
        btnERADijagram.setText("ERA dijagram");
        btnERADijagram.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnERADijagram.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        btnERADijagram.setOpaque(true);
        btnERADijagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnERADijagramMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnERADijagramMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnERADijagramMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistracija, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrijava, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportPodataka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnERADijagram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGitHub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblPrijava)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistracija)
                .addGap(149, 149, 149)
                .addComponent(btnImportPodataka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnERADijagram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGitHub)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrijavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrijavaMouseClicked
        pressedTab = PomagalaIzbornika.setClickedEffect(tabovi, (JLabel)evt.getComponent(), menuListener);
    }//GEN-LAST:event_lblPrijavaMouseClicked

    private void lblRegistracijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistracijaMouseClicked
        pressedTab = PomagalaIzbornika.setClickedEffect(tabovi, (JLabel)evt.getComponent(), menuListener);
    }//GEN-LAST:event_lblRegistracijaMouseClicked

    private void lblPrijavaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrijavaMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_lblPrijavaMouseExited

    private void lblPrijavaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrijavaMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_lblPrijavaMouseEntered

    private void lblRegistracijaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistracijaMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_lblRegistracijaMouseEntered

    private void lblRegistracijaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistracijaMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_lblRegistracijaMouseExited

    private void btnGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGitHubMouseClicked
        try {
            Runtime.getRuntime().exec("cmd /c start https://github.com/valentinkatic/LjetniZadatak ");
        } catch (IOException ex) {
            Logger.getLogger(PanelStart.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_btnGitHubMouseClicked

    private void btnGitHubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGitHubMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_btnGitHubMouseEntered

    private void btnGitHubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGitHubMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_btnGitHubMouseExited

    private void btnERADijagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnERADijagramMouseClicked
        try {
            String fileName = "/res/dijagram.png";
            File f = new File(getClass().getResource(fileName).getFile());
            Desktop dt = Desktop.getDesktop();
            dt.open(f);           
        } catch (IOException ex) {
            Logger.getLogger(PanelStart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnERADijagramMouseClicked

    private void btnERADijagramMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnERADijagramMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_btnERADijagramMouseEntered

    private void btnERADijagramMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnERADijagramMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_btnERADijagramMouseExited

    private void btnImportPodatakaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportPodatakaMouseExited
        PomagalaIzbornika.setUnHoverEffect(tabovi.get(pressedTab), (JLabel)evt.getComponent());
    }//GEN-LAST:event_btnImportPodatakaMouseExited

    private void btnImportPodatakaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportPodatakaMouseEntered
        PomagalaIzbornika.setHoverEffect((JLabel)evt.getComponent());
    }//GEN-LAST:event_btnImportPodatakaMouseEntered

    private void btnImportPodatakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportPodatakaMouseClicked
        pressedTab = PomagalaIzbornika.setClickedEffect(tabovi, (JLabel)evt.getComponent(), menuListener);
    }//GEN-LAST:event_btnImportPodatakaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnERADijagram;
    private javax.swing.JLabel btnGitHub;
    private javax.swing.JLabel btnImportPodataka;
    private javax.swing.JLabel lblPrijava;
    private javax.swing.JLabel lblRegistracija;
    // End of variables declaration//GEN-END:variables
}
