/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import katic.ljetnizadatak.controller.ObradaJelo;
import katic.ljetnizadatak.controller.ObradaKategorijaJela;
import katic.ljetnizadatak.controller.ObradaRestoran;
import katic.ljetnizadatak.model.Jelo;
import katic.ljetnizadatak.model.KategorijaJela;
import katic.ljetnizadatak.model.Restoran;
import static katic.ljetnizadatak.view.FormaAplikacije.JELO;
import static katic.ljetnizadatak.view.FormaAplikacije.LISTA_KATEGORIJA;
import katic.pomocno.JeloListener;
import katic.pomocno.MenuListener;

/**
 *
 * @author Valentin
 */
public class PanelIzbornikOdabraneKategorije extends javax.swing.JPanel {

    private JPanel desniPanel = FormaAplikacije.desniPanel;
    
    private ObradaKategorijaJela obradaKategorijaJela; 
    private ObradaJelo obradaJelo;
    private Restoran restoran;
    private KategorijaJela kategorijaJela;
    private Jelo jelo;
    private MenuListener menuListener;
    private KategorijaJela entitet;
    
    private PanelJelo panelJelo;
    
    public PanelIzbornikOdabraneKategorije(Restoran restoran, KategorijaJela kategorijaJela, MenuListener menuListener) {
        this.kategorijaJela = kategorijaJela;
        this.restoran = restoran;
        this.menuListener = menuListener;
       
        initComponents();
        
        JeloListener jeloListener = new JeloListener() {
            @Override
            public void jeloObrisano() {
                ucitaj();
                lista.clearSelection();
                ucitajJelo(null);
            }

            @Override
            public void jeloSpremljeno(Jelo jelo) {
                ucitaj();
                if (kategorijaJela.equals(jelo.getKategorijaJela())){
                    lista.setSelectedValue(jelo, true);
                } else {
                    menuListener.odabranaKategorija(restoran, jelo.getKategorijaJela());
                }
                ucitajJelo(jelo);                
            }
        };
        
        lblBack.setText(kategorijaJela.getNaziv());
        panelJelo = new PanelJelo(restoran, null, kategorijaJela, jeloListener);
        obradaKategorijaJela = new ObradaKategorijaJela();
        obradaJelo = new ObradaJelo();
        ucitaj();
    }
    
     private void ucitaj(){       
        DefaultListModel<Jelo> m = new DefaultListModel<>();
        lista.setModel(m);
        for (Jelo j: obradaJelo.getJela(kategorijaJela, restoran)){
            m.addElement(j);
        }
        
        if (entitet!=null){            
            lista.setSelectedValue(entitet, false);
        }
        
         desniPanel.add(panelJelo, JELO);
         ((CardLayout) desniPanel.getLayout()).show(desniPanel, JELO);
    }
     
    private void ucitajJelo(Jelo j){
        panelJelo.setJelo(j);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        lblBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 40, 55));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        lista.setBackground(new java.awt.Color(38, 40, 55));
        lista.setToolTipText("");
        lista.setCellRenderer(new katic.ljetnizadatak.view.renderer.RendererJelaULijevomPanelu());
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        lblBack.setBackground(new java.awt.Color(38, 40, 55));
        lblBack.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        lblBack.setForeground(new java.awt.Color(204, 204, 204));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        lblBack.setText("Kategorija jela");
        lblBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 1));
        lblBack.setOpaque(true);
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblBack)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        try{
            jelo = lista.getSelectedValue();
            panelJelo.setJelo(jelo);
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_listaValueChanged

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        menuListener.onBackPressed(LISTA_KATEGORIJA);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        lblBack.setBackground(new Color(38,40,55));
    }//GEN-LAST:event_lblBackMouseExited

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        lblBack.setBackground(new Color(103,33,122));
    }//GEN-LAST:event_lblBackMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JList<Jelo> lista;
    // End of variables declaration//GEN-END:variables
}
