/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.util.List;
import javax.swing.DefaultListModel;
import katic.ljetnizadatak.controller.ObradaJelo;
import katic.ljetnizadatak.model.Jelo;
import katic.ljetnizadatak.model.KategorijaJela;
import katic.ljetnizadatak.model.Korisnik;
import katic.ljetnizadatak.model.Restoran;
import katic.ljetnizadatak.view.renderer.RendererJelaUKategoriji;

/**
 *
 * @author Valentin
 */
public class PanelOdabraneKategorije extends javax.swing.JPanel {

    private Korisnik korisnik;
    private Restoran restoran;
    private KategorijaJela kategorijaJela;
    private ObradaJelo obradaJelo;
    private List<Jelo> jela;
    
    public PanelOdabraneKategorije(Korisnik korisnik, Restoran restoran, KategorijaJela kategorijaJela) {
        this.korisnik = korisnik;
        this.restoran = restoran;
        this.kategorijaJela = kategorijaJela;
        initComponents();
        
        this.obradaJelo = new ObradaJelo();
        
        if (kategorijaJela!=null){
            lblNaziv.setText(kategorijaJela.getNaziv());
            ucitaj();
        }        
    }
    
    private void ucitaj(){
        jela = obradaJelo.getJela(kategorijaJela, restoran);
        DefaultListModel<Jelo> m = new DefaultListModel<Jelo>();
        lista.setModel(m);
        for (Jelo j: jela){
            m.addElement(j);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaziv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setBackground(new java.awt.Color(58, 56, 77));

        lblNaziv.setBackground(new java.awt.Color(38, 40, 55));
        lblNaziv.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        lblNaziv.setForeground(new java.awt.Color(204, 204, 204));
        lblNaziv.setText("Odaberite kategoriju");
        lblNaziv.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 1));

        jScrollPane1.setBorder(null);

        lista.setBackground(new java.awt.Color(58, 56, 77));
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setCellRenderer(new RendererJelaUKategoriji());
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNaziv)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JList<Jelo> lista;
    // End of variables declaration//GEN-END:variables
}
