/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JTextField;
import katic.pomocno.PomagalaIzbornika;

/**
 *
 * @author valentin.katic
 */
public class PanelRegistracije extends javax.swing.JPanel {

    private static final String KORISNIK = "KORISNIK";
    private static final String RESTORAN = "RESTORAN";
    
    private CardLayout cardLayout;
    private int pressedTab = 0;
    /**
     * Creates new form PanelRegistracije
     */
    public PanelRegistracije() {
        initComponents();
        cardLayout = (CardLayout) panelTijela.getLayout();
        
        panelTijela.setBounds(0, 25, 400, 500);
        PanelRegistracijeKorisnika panelRegistracijeKorisnika = new PanelRegistracijeKorisnika();
        panelRegistracijeKorisnika.setSize(400,475);
        PanelRegistracijeRestorana panelRegistracijeRestorana = new PanelRegistracijeRestorana();
        panelRegistracijeRestorana.setSize(400,475);
        
        panelTijela.add(panelRegistracijeKorisnika, KORISNIK);
        panelTijela.add(panelRegistracijeRestorana, RESTORAN);
        
        cardLayout.show(panelTijela, KORISNIK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        panelTijela = new javax.swing.JPanel();

        setBackground(new java.awt.Color(58, 56, 77));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setLayout(new java.awt.GridBagLayout());

        jTextField1.setBackground(new java.awt.Color(58, 56, 77));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Registracija korisnika");
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setMaximumSize(new java.awt.Dimension(110, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(110, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        add(jTextField1, gridBagConstraints);

        jTextField2.setBackground(new java.awt.Color(38, 40, 55));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Registracija restorana");
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.setMaximumSize(new java.awt.Dimension(110, 25));
        jTextField2.setMinimumSize(new java.awt.Dimension(110, 25));
        jTextField2.setName(""); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField2MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jTextField2, gridBagConstraints);

        panelTijela.setBackground(new java.awt.Color(58, 56, 77));
        panelTijela.setMaximumSize(new java.awt.Dimension(400, 475));
        panelTijela.setMinimumSize(new java.awt.Dimension(400, 475));
        panelTijela.setPreferredSize(new java.awt.Dimension(400, 475));
        panelTijela.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(panelTijela, gridBagConstraints);
        panelTijela.getAccessibleContext().setAccessibleParent(panelTijela);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        PomagalaIzbornika.setHoverTabColor(jTextField1);
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        if (pressedTab == 0){
            PomagalaIzbornika.setPressedTabColor(jTextField1);
        } else {
            PomagalaIzbornika.setDefaultTabColor(jTextField1);
        }
    }//GEN-LAST:event_jTextField1MouseExited

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        PomagalaIzbornika.setPressedTabColor(jTextField1);
        PomagalaIzbornika.setDefaultTabColor(jTextField2);
        if (pressedTab == 1){
            pressedTab = 0;
            promijeniPanel(KORISNIK);
        }      
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        PomagalaIzbornika.setHoverTabColor(jTextField2);
    }//GEN-LAST:event_jTextField2MouseEntered

    private void jTextField2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseExited
        if (pressedTab == 1){
            PomagalaIzbornika.setPressedTabColor(jTextField2);
        } else {
            PomagalaIzbornika.setDefaultTabColor(jTextField2);
        }
    }//GEN-LAST:event_jTextField2MouseExited

    private void jTextField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MousePressed
        PomagalaIzbornika.setPressedTabColor(jTextField2);
        PomagalaIzbornika.setDefaultTabColor(jTextField1);
        if (pressedTab ==0){
            pressedTab = 1;
            promijeniPanel(RESTORAN);
        }
    }//GEN-LAST:event_jTextField2MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void promijeniPanel(String panel){
        cardLayout.next(panelTijela);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panelTijela;
    // End of variables declaration//GEN-END:variables
}
