/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.awt.Color;
import javax.swing.DefaultListModel;
import katic.ljetnizadatak.controller.ObradaKategorijaJela;
import katic.ljetnizadatak.model.KategorijaJela;
import katic.ljetnizadatak.model.Restoran;
import katic.ljetnizadatak.view.renderer.RendererKategorijaJelaUDesnomPanelu;
import katic.pomocno.MenuListener;

/**
 *
 * @author valentin.katic
 */
public class PanelKategorijeJela extends javax.swing.JPanel {

    private ObradaKategorijaJela obrada;
    private Restoran restoran;
    private KategorijaJela kategorijaJela;
    /**
     * Creates new form PanelRestoran
     */
    private MenuListener menuListener;
    
    public PanelKategorijeJela(MenuListener menuListener, Restoran restoran) {
        initComponents();
        this.menuListener = menuListener;
        this.restoran = restoran;
        
        this.obrada = new ObradaKategorijaJela();      
        ucitaj();
    }

    private void ucitaj(){
        DefaultListModel<KategorijaJela> m = new DefaultListModel<KategorijaJela>();       
        lista.setModel(m);
        for (KategorijaJela k: obrada.getKategorijeJela()){
            m.addElement(k);
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        lblNovaKategorija = new javax.swing.JLabel();

        setBackground(new java.awt.Color(58, 56, 77));
        setForeground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBorder(null);

        lista.setBackground(new java.awt.Color(58, 56, 77));
        lista.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lista.setFont(new java.awt.Font("Century Gothic", 0, 28)); // NOI18N
        lista.setForeground(new java.awt.Color(204, 204, 204));
        lista.setToolTipText("");
        lista.setCellRenderer(new RendererKategorijaJelaUDesnomPanelu());
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        lblNovaKategorija.setBackground(new java.awt.Color(58, 56, 77));
        lblNovaKategorija.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblNovaKategorija.setForeground(new java.awt.Color(255, 255, 255));
        lblNovaKategorija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/add.png"))); // NOI18N
        lblNovaKategorija.setText("Kreiraj novu kategoriju");
        lblNovaKategorija.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        lblNovaKategorija.setOpaque(true);
        lblNovaKategorija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovaKategorijaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNovaKategorijaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNovaKategorijaMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNovaKategorija)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNovaKategorija)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        if (lista.getSelectedValue()==null){
            return;
        }
        kategorijaJela = lista.getSelectedValue();
        menuListener.odabranaKategorija(restoran, kategorijaJela);
        lista.clearSelection();
    }//GEN-LAST:event_listaValueChanged

    private void lblNovaKategorijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovaKategorijaMouseClicked
        
    }//GEN-LAST:event_lblNovaKategorijaMouseClicked

    private void lblNovaKategorijaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovaKategorijaMouseEntered
        lblNovaKategorija.setBackground(new Color(68,23,80));
    }//GEN-LAST:event_lblNovaKategorijaMouseEntered

    private void lblNovaKategorijaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovaKategorijaMouseExited
        lblNovaKategorija.setBackground(new Color(58,56,77));
    }//GEN-LAST:event_lblNovaKategorijaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNovaKategorija;
    private javax.swing.JList<KategorijaJela> lista;
    // End of variables declaration//GEN-END:variables
}
