/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package katic.ljetnizadatak.view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import katic.ljetnizadatak.controller.ObradaAdresaDostave;
import katic.ljetnizadatak.controller.ObradaNarudzba;
import katic.ljetnizadatak.controller.ObradaNarudzbaJelo;
import katic.ljetnizadatak.model.AdresaDostave;
import katic.ljetnizadatak.model.Korisnik;
import katic.ljetnizadatak.model.Narudzba;
import katic.ljetnizadatak.model.NarudzbaJelo;
import katic.ljetnizadatak.view.renderer.RendererJelaUKategoriji;
import katic.ljetnizadatak.view.renderer.RendererOtvoreneNarudzbe;
import katic.pomocno.Iznimka;
import katic.pomocno.KorisnikListener;
import katic.pomocno.MenuListener;

/**
 *
 * @author Valentin
 */
public class PanelOtvoreneNarudzbe extends javax.swing.JPanel {
   
    private Narudzba narudzba;
    private Narudzba novaNarudzba = null;
    private ObradaNarudzba obradaNarudzba = null;
    private ObradaAdresaDostave obradaAdresaDostave = null;
    private ObradaNarudzbaJelo obradaNarudzbaJelo = null;
    private MenuListener menuListener;
    private KorisnikListener korisnikListener = null;
    private Korisnik korisnik;
    
    public PanelOtvoreneNarudzbe(Narudzba narudzba, MenuListener menuListener) {
        this.narudzba = narudzba;
        this.menuListener = menuListener;
        initComponents();
             
        pnlDodajUKosaricu.setVisible(false);
        ucitaj();
    }
    
    public PanelOtvoreneNarudzbe(Narudzba narudzba, Korisnik korisnik, MenuListener menuListener, KorisnikListener korisnikListener) {
        this.narudzba = narudzba;
        this.korisnik = korisnik;
        this.menuListener = menuListener;
        this.korisnikListener = korisnikListener;
        
        novaNarudzba = new Narudzba();
        novaNarudzba.setKorisnik(korisnik);
        novaNarudzba.setRestoran(narudzba.getRestoran());
        novaNarudzba.setAdresaDostave(narudzba.getAdresaDostave());
        novaNarudzba.setNova(true);
        
        this.obradaNarudzba = new ObradaNarudzba();
        this.obradaAdresaDostave = new ObradaAdresaDostave();
        this.obradaNarudzbaJelo  = new ObradaNarudzbaJelo();
        initComponents();
             
        ucitaj();
    }
    
    private void ucitaj(){ 
        DefaultListModel<NarudzbaJelo> m = new DefaultListModel<NarudzbaJelo>();
        lista.setModel(m);       
        
        double suma = 0;
        for (NarudzbaJelo nj: narudzba.getNarudzbaJela()){
            m.addElement(nj);    
            suma += nj.getKolicina()*nj.getJelo().getCijena();
        }
        
        lblSuma.setText(String.format("%.2f kn", suma));
        lblAdresa.setText(narudzba.getAdresaDostave().toString());
        lblKontaktBroj.setText(narudzba.getKorisnik().getKontaktBroj());
    }    
    
    public void ucitajNarudzbu(Narudzba narudzba){
        this.narudzba = narudzba;
        ucitaj();
    }
    
    private void postaviAdresu(){
        List<AdresaDostave> adreseDostave = obradaAdresaDostave.getAdreseDostave(korisnik);
        if (adreseDostave==null){
            JOptionPane.showMessageDialog(this, "Dodajte barem jednu adresu preko izbornika moji podaci", "Nema spremljenih adresa", JOptionPane.WARNING_MESSAGE);         
        } else {
            AdresaDostave[] choices = adreseDostave.toArray(new AdresaDostave[adreseDostave.size()]);
            AdresaDostave adresa = new DialogListeAdresa().main(choices);
            if (adresa==null){
                return;
            }
            novaNarudzba.setAdresaDostave(adresa);
            lblAdresa.setText(adresa.toString());            
        }
    }
    
    private void dodajJelaUNarudzbu(){
        novaNarudzba.setNarudzbaJela(new ArrayList<>());
        for (NarudzbaJelo nj: narudzba.getNarudzbaJela()){
            NarudzbaJelo narudzbaJelo = new NarudzbaJelo();
            narudzbaJelo.setJelo(nj.getJelo());
            narudzbaJelo.setKolicina(nj.getKolicina());
            narudzbaJelo.setNarudzba(novaNarudzba);
            novaNarudzba.getNarudzbaJela().add(narudzbaJelo);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaziv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        lblSuma = new javax.swing.JLabel();
        lblNaziv2 = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        lblNaziv4 = new javax.swing.JLabel();
        lblNaziv5 = new javax.swing.JLabel();
        lblKontaktBroj = new javax.swing.JLabel();
        pnlDodajUKosaricu = new javax.swing.JPanel();
        lblDodajUKošaricu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(58, 56, 77));

        lblNaziv.setBackground(new java.awt.Color(58, 56, 77));
        lblNaziv.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        lblNaziv.setForeground(new java.awt.Color(204, 204, 204));
        lblNaziv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/back.png"))); // NOI18N
        lblNaziv.setText("Povratak");
        lblNaziv.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblNaziv.setOpaque(true);
        lblNaziv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNazivMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNazivMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNazivMouseEntered(evt);
            }
        });

        jScrollPane1.setBorder(null);

        lista.setBackground(new java.awt.Color(58, 56, 77));
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setCellRenderer(new RendererOtvoreneNarudzbe());
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        lblSuma.setBackground(new java.awt.Color(58, 56, 77));
        lblSuma.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblSuma.setForeground(new java.awt.Color(204, 204, 204));
        lblSuma.setText("0.00 kn");
        lblSuma.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblSuma.setOpaque(true);

        lblNaziv2.setBackground(new java.awt.Color(58, 56, 77));
        lblNaziv2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNaziv2.setForeground(new java.awt.Color(204, 204, 204));
        lblNaziv2.setText("Kontakt broj: ");
        lblNaziv2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblNaziv2.setOpaque(true);

        lblAdresa.setBackground(new java.awt.Color(58, 56, 77));
        lblAdresa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAdresa.setForeground(new java.awt.Color(204, 204, 204));
        lblAdresa.setText("adresa dostave");
        lblAdresa.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblAdresa.setOpaque(true);
        lblAdresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdresaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdresaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdresaMouseEntered(evt);
            }
        });

        lblNaziv4.setBackground(new java.awt.Color(58, 56, 77));
        lblNaziv4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblNaziv4.setForeground(new java.awt.Color(204, 204, 204));
        lblNaziv4.setText("Suma:");
        lblNaziv4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblNaziv4.setOpaque(true);

        lblNaziv5.setBackground(new java.awt.Color(58, 56, 77));
        lblNaziv5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNaziv5.setForeground(new java.awt.Color(204, 204, 204));
        lblNaziv5.setText("Adresa dostave: ");
        lblNaziv5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblNaziv5.setOpaque(true);

        lblKontaktBroj.setBackground(new java.awt.Color(58, 56, 77));
        lblKontaktBroj.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblKontaktBroj.setForeground(new java.awt.Color(204, 204, 204));
        lblKontaktBroj.setText("kontakt broj");
        lblKontaktBroj.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 1));
        lblKontaktBroj.setOpaque(true);

        pnlDodajUKosaricu.setBackground(new java.awt.Color(125, 86, 192));
        pnlDodajUKosaricu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDodajUKosaricuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDodajUKosaricuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDodajUKosaricuMouseEntered(evt);
            }
        });

        lblDodajUKošaricu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblDodajUKošaricu.setForeground(new java.awt.Color(255, 255, 255));
        lblDodajUKošaricu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDodajUKošaricu.setText("Dodaj u košaricu");

        javax.swing.GroupLayout pnlDodajUKosaricuLayout = new javax.swing.GroupLayout(pnlDodajUKosaricu);
        pnlDodajUKosaricu.setLayout(pnlDodajUKosaricuLayout);
        pnlDodajUKosaricuLayout.setHorizontalGroup(
            pnlDodajUKosaricuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDodajUKošaricu, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        pnlDodajUKosaricuLayout.setVerticalGroup(
            pnlDodajUKosaricuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDodajUKošaricu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNaziv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblNaziv5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNaziv4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNaziv2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKontaktBroj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(pnlDodajUKosaricu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNaziv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv4)
                    .addComponent(lblSuma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv5)
                    .addComponent(lblAdresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNaziv2)
                        .addComponent(lblKontaktBroj))
                    .addComponent(pnlDodajUKosaricu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        if (lista.getSelectedValue()==null){
            return;
        }       
    }//GEN-LAST:event_listaValueChanged

    private void lblNazivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNazivMouseClicked
        menuListener.onBackPressed(FormaAplikacije.ODABRANA_NARUDZBA);
    }//GEN-LAST:event_lblNazivMouseClicked

    private void lblNazivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNazivMouseEntered
        lblNaziv.setBackground(new Color(68,23,80));
    }//GEN-LAST:event_lblNazivMouseEntered

    private void lblNazivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNazivMouseExited
        lblNaziv.setBackground(new Color(58,56,77));
    }//GEN-LAST:event_lblNazivMouseExited

    private void lblAdresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdresaMouseEntered
        if (korisnik!=null){
            lblAdresa.setBackground(new Color(68,23,80));
        }
    }//GEN-LAST:event_lblAdresaMouseEntered

    private void lblAdresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdresaMouseClicked
        if (korisnik!=null){
            postaviAdresu();
        }
    }//GEN-LAST:event_lblAdresaMouseClicked

    private void lblAdresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdresaMouseExited
        if (korisnik!=null){
            lblAdresa.setBackground(new Color(58,56,77));
        }
    }//GEN-LAST:event_lblAdresaMouseExited

    private void pnlDodajUKosaricuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDodajUKosaricuMouseClicked
        try {
            obradaNarudzba.obrisiNeizvrseneNarudzbe(korisnik);            
            novaNarudzba = obradaNarudzba.spremi(novaNarudzba);
            dodajJelaUNarudzbu();
            novaNarudzba = obradaNarudzba.spremi(novaNarudzba);
            obradaNarudzbaJelo.spremi(novaNarudzba.getNarudzbaJela());
            korisnikListener.dodanaStaraNarudzba();
        } catch (Iznimka i){
            i.printStackTrace();
        }
    }//GEN-LAST:event_pnlDodajUKosaricuMouseClicked

    private void pnlDodajUKosaricuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDodajUKosaricuMouseExited
        pnlDodajUKosaricu.setBackground(new Color(125,86,192));
    }//GEN-LAST:event_pnlDodajUKosaricuMouseExited

    private void pnlDodajUKosaricuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDodajUKosaricuMouseEntered
        pnlDodajUKosaricu.setBackground(new Color(103,33,122));
    }//GEN-LAST:event_pnlDodajUKosaricuMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblDodajUKošaricu;
    private javax.swing.JLabel lblKontaktBroj;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblNaziv2;
    private javax.swing.JLabel lblNaziv4;
    private javax.swing.JLabel lblNaziv5;
    private javax.swing.JLabel lblSuma;
    private javax.swing.JList<NarudzbaJelo> lista;
    private javax.swing.JPanel pnlDodajUKosaricu;
    // End of variables declaration//GEN-END:variables
}
